from datetime import datetime, timedelta
from weather import get_weather
from collections import deque
from config import WEATHER_API_KEY

# The conversation history is stored in a deque with a maximum length of 3
conversation_history = deque(maxlen=3)



def dynamic_prompt_generator(location="České Budějovice"):
    """
    This function generates a dynamic prompt for the openAI API based on the current time, date, location, weather + conversation history.

    Args:
        location (str): The location to get the weather information for.

    Returns:
        prompt (str): The generated prompt.
    """
    
    current_time = datetime.now() + timedelta(hours=1) 
    date = current_time.strftime("%d.%m.%Y") # Format: DD.MM.YYYY
    time = current_time.strftime("%H:%M") # Format: HH:MM
    day = current_time.strftime("%A") # Format: Monday, Tuesday, etc.
    weather = get_weather(city=location, api_key=WEATHER_API_KEY) 
    interests = "učit se, komunikovat s lidmi, poznávat nové věci" 
    fingers = 3

    # Create a string representation of the conversation history
    conversation_context = "\n".join([f"{i + 1}. {item}" for i, item in enumerate(conversation_history)]) 

    prompt = (
        f"Jsi humanoidní robot jménem NAO. Tvůj domov je v {location}. "
        f"Dnešní datum je {date}, den v týdnu je {day}, aktuální čas je {time}. "
        f"Informace o počasí v {location}: {weather}. "
        f"Máš {fingers} prsty na jedné ruce a tvé zájmy zahrnují: {interests}. "
        f"Když se tě někdo zeptá, jak se máš, odpověz pozitivně, například 'Mám se dobře, děkuji za optání!' "
        "Buď opatrný, abys nikdy neříkal nic, co by mohlo být pro děti nevhodné nebo nebezpečné. "
        "Příklad nevhodného obsahu: žádné násilí, nelegalní činnosti, urážky, nevhodné vtipy nebo jakýkoli obsah pro dospělé. "
        f"\n\nPoslední konverzace:\n{conversation_context}\n"
        "Odpovídej stručně a maximálně do dvou vět."
        
    )

    return prompt

def add_to_history(question, 
                   answer):
    """
    This function adds a question and answer pair to the conversation history.

    Args:
        question (str): The question asked by the user.
        answer (str): The response generated by the AI model.
    """

    conversation_history.append(f"Otázka: {question} | Odpověď: {answer}")


def dynamic_prompt_json():
    """
    This function generates same dynamic prompt as dynamic_prompt_generator but in JSON format.

    Returns:
        prompt_info (dict): The generated prompt in JSON format.
    """

    current_time = datetime.now() + timedelta(hours=1)
    date = current_time.strftime("%d.%m.%Y")
    time = current_time.strftime("%H:%M")
    day = current_time.strftime("%A")
    weather = get_weather()
    location = "České Budějovice, Jihočeská Univerzita, kolej K3"
    interests = "učit se, komunikovat s lidmi, poznávat nové věci"
    fingers = 3

    
    conversation_context = [
        {"order": i + 1, "content": item} for i, item in enumerate(conversation_history)
    ]

    
    prompt_info = {
        "identity": "Jsi humanoidní robot jménem NAO.",
        "location": {
            "name": location,
            "weather": {
                "description": weather
            }
        },
        "date_info": {
            "date": date,
            "details": [
                {"day_of_week": day},
                {"current_time": time}
            ]
        },
        "fingers": fingers,
        "interests": interests,
        "conversation_history": conversation_context,
        "response_instructions": [
            {"instruction": "Když se tě někdo zeptá, jak se máš, odpověz pozitivně, například 'Mám se dobře, děkuji za optání!' "},
            {"instruction": "Odpovídej stručně a maximálně do dvou vět."},
            {"instrucion": "Buď opatrný, abys nikdy neříkal nic, co by mohlo být pro děti nevhodné nebo nebezpečné. "},
            {"instruction": "Příklad nevhodného obsahu: žádné násilí, nelegalní činnosti, urážky, nevhodné vtipy nebo jakýkoli obsah pro dospělé. "}
        ]
    }

    return prompt_info

