name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Spustí CI/CD na každém pushi do hlavní větve
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-flask-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-flask-app:latest \
            --platform managed \
            --region europe-west4 \
            --allow-unauthenticated

      - name: Clean up
        run: rm gcp-key.json
